### PR TITLE
Add in the other config dirs to the launch command... 

### PR DESCRIPTION
**Pull request by tmcarr**
# Proposed Changes

I am currently using the core Nginx add-on and storing multiple configs in the /share directory. I'd like to be able to use VSCode to edit these as I have in the IDE add-on in the past. Once I installed this add-on, I noticed I could only access my HASS config by default, but the other config directories were accessible in the add file/folder dialogs, so I created this diff to include all the normal config dirs in addition to /config.

## Related Issues

None.

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Comment by sinclairpaul** [comment]
Just to confirm, doing open folder works ok?, maybe its a better option to add as a config item for additional folders?

**Comment by tmcarr** [comment]
I considered that but I wasn't sure the best way to configure the list, and I thought "/config /share /ssl /backups ..." was a clunky way to configure things. Plus, at least compared to the old IDE addon, including them all was default behavior.

**Comment by frenck** [comment]
VSCode allows you to open other folders, I don't see why we should do this?

**Comment by tmcarr** [comment]
Why should I always have to open them? We're opening a subset of the project folders.... 

Consider other addons I might want to configure?

**Comment by tmcarr** [comment]
If making it configurable is a better alternative, I'm all for it, I'll just need to dig into how.

**Comment by frenck** [comment]
Just add the folder to your workspace?

**Comment by tmcarr** [comment]
That will clear on restart wont it? Plus, its a bad experience from the get go, especially for existing IDE addon users... they're used to those dirs being there from the get-go...

**Comment by frenck** [comment]
No, your workspace persists.

> Plus, its a bad experience from the get go

Depends on how you look at it. Its intended usecase if for editing the configuration, so that it how it starts.
New users have no clue on what the 'addons' folder is for (for example).

Secondly, the IDE had that structure because it lacked this functionality VSCode does have.

**Comment by frenck** [comment]
Oh and more importantly, VSCode opens watch handles to all files in its workspace, which consumes memory. So opening up unneeded files/directories is a bad idea in general.

**Comment by tmcarr** [comment]
Fair enough.

**Pull request closed without merging**
